import type { CompletionOptions, CompletionStream } from '../types.js';

/** A single conversation — TZ §9.1. */
export interface Chat {
  /**
   * Set by the caller, not force-generated by the library (except a
   * convenient default in `createChat()`, TZ §9.6) — lets a host app reuse
   * its own chat ids directly, without an id-mapping layer.
   */
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  metadata?: Record<string, unknown>;
}

/** A single message within a chat — TZ §9.1. */
export interface ChatMessage {
  /** Set by the caller; unique per `(chatId, id)`, not globally — TZ §9.1. */
  id: string;
  chatId: string;
  role: 'system' | 'user' | 'assistant';
  content: string;
  /**
   * `'complete'` — finished normally. `'cancelled'` — generation was
   * aborted via `AbortSignal`; `content` is the partial response and is
   * kept, not discarded. `'error'` — generation failed at runtime;
   * `content` may be empty. User messages are always `'complete'`. TZ §9.8.
   */
  status: 'complete' | 'cancelled' | 'error';
  createdAt: string;
  tokenCount?: number;
  metadata?: Record<string, unknown>;
}

/**
 * Mandatory MVP surface — library as source of truth for chat data
 * (Mode A, TZ §9.6). Implemented by `LocalAiClient`, backed by
 * `ConversationStore`.
 */
export interface ConversationApi {
  createChat(options?: {
    id?: string;
    title?: string;
    systemPrompt?: string;
    metadata?: Record<string, unknown>;
  }): Promise<Chat>;
  listChats(options?: { limit?: number; offset?: number; orderBy?: 'updatedAt' | 'createdAt' }): Promise<Chat[]>;
  getChat(chatId: string): Promise<Chat | null>;
  renameChat(chatId: string, title: string): Promise<void>;
  /** Cascades to messages and the chat's session-cache file, TZ §9.2. */
  deleteChat(chatId: string): Promise<void>;
  getMessages(chatId: string, options?: { limit?: number; before?: string }): Promise<ChatMessage[]>;

  /**
   * Loads chat history, streams a completion, and persists both the user
   * and assistant messages itself (custom ids accepted for idempotent
   * retry after a network failure). Cancel/error semantics: TZ §9.8.
   * Context-window handling: TZ §9.7.
   */
  sendMessage(
    chatId: string,
    text: string,
    options?: {
      userMessageId?: string;
      assistantMessageId?: string;
      completionOptions?: CompletionOptions;
      signal?: AbortSignal;
    },
  ): CompletionStream<ChatMessage>;
}

/**
 * Optional extension — library as a context mirror over externally owned
 * history (Mode B, TZ §9.6). The same `LocalAiClient` implements it; apps
 * that don't need sync simply never call these. Kept as a separate type
 * (not folded into `ConversationApi`) to avoid inflating the surface for
 * consumers who only need Mode A — see TZ §9.2, open question §16.16 on
 * whether this ships in the first release at all.
 */
export interface ConversationSyncApi {
  /**
   * Idempotent upsert by id: creates the chat if missing; if it already
   * exists, only `title`/`metadata`/`updatedAt` are updated — messages are
   * never touched or lost. TZ §9.2.
   */
  upsertChat(chat: {
    id: string;
    title: string;
    createdAt?: string;
    updatedAt?: string;
    metadata?: Record<string, unknown>;
  }): Promise<Chat>;

  /**
   * Idempotent append: dedups by `(chatId, message.id)`, silently skipping
   * (never overwriting — content is immutable after first write, TZ
   * §9.5/§9.6) messages that already exist. Creates the chat via an implicit
   * minimal `upsertChat` if `chatId` doesn't exist yet. Insert order doesn't
   * matter — reads are sorted by `createdAt`. TZ §9.2.
   */
  appendMessages(
    chatId: string,
    messages: Array<{
      id: string;
      role: ChatMessage['role'];
      content: string;
      status?: ChatMessage['status'];
      createdAt: string;
      tokenCount?: number;
      metadata?: Record<string, unknown>;
    }>,
  ): Promise<{ inserted: number; skippedExisting: number }>;

  /**
   * Syncs an edit made to an already-stored message's content in the host
   * app's own DB (Phase 8, `docs/decisions.md` #7a) — content is otherwise
   * immutable after first write (TZ §9.5). Only the fields given in
   * `updates` are changed; omitted fields are left as-is. Invalidates the
   * chat's session-cache file (its KV state was built from the old
   * content). Throws {@link MessageNotFoundError} if `(chatId, messageId)`
   * doesn't exist — an explicit sync call naming a specific message that
   * turns out to be missing signals real drift between the host app's DB
   * and `local-ai`'s copy, unlike `appendMessages`' routine dedup-by-id.
   */
  updateMessage(
    chatId: string,
    messageId: string,
    updates: { content?: string; status?: ChatMessage['status']; tokenCount?: number; metadata?: Record<string, unknown> },
  ): Promise<ChatMessage>;

  /**
   * Syncs deletions made in the host app's own DB (Phase 8, `docs/decisions.md`
   * #7a). Unlike {@link updateMessage}, ids that don't exist are silently
   * not counted — a bulk delete-sync call is expected to sometimes name ids
   * already gone (e.g. a repeated/overlapping sync batch), matching
   * `appendMessages`' idempotent-batch spirit. Invalidates the chat's
   * session-cache file if anything was actually deleted.
   */
  deleteMessages(chatId: string, messageIds: string[]): Promise<{ deleted: number }>;
}

/**
 * One chat's full exportable state — Phase 8 (`docs/decisions.md`'s "Full-text
 * search"/"Export/backup" section). Deliberately shaped to feed straight
 * back into {@link ConversationSyncApi.upsertChat}/`appendMessages` for a
 * round-trip restore — no separate import method exists on purpose.
 */
export interface ChatExport {
  chat: Chat;
  messages: ChatMessage[];
}

/** Export/backup — Phase 8 addition, no TZ section (see `docs/decisions.md`). Implemented by `LocalAiClient`, backed by `ConversationStore`. */
export interface ChatExportApi {
  /** Resolves `null` if no chat with this id exists. */
  exportChat(chatId: string): Promise<ChatExport | null>;
  /** Exports every chat (paginated the same way as `listChats()`). */
  exportChats(options?: { limit?: number; offset?: number }): Promise<ChatExport[]>;
}

/** One full-text search hit — Phase 8 addition, no TZ section (see `docs/decisions.md`). */
export interface ChatSearchHit {
  message: ChatMessage;
  /** Highlighted excerpt around the match — only populated on the FTS5 path, `undefined` on the `LIKE` fallback. */
  snippet?: string;
}

/**
 * Full-text search across one or all chats — Phase 8 addition, no TZ
 * section (see `docs/decisions.md`'s "Full-text search" entry).
 * Implemented by `LocalAiClient`, backed by `MessageSearchIndex`
 * (`createMessageSearchIndex()` picks FTS5 or a `LIKE` fallback
 * opportunistically, same shape as `VectorStore`'s `sqlite-vec`/brute-force
 * split).
 */
export interface ChatSearchApi {
  searchMessages(query: string, options?: { chatId?: string; limit?: number }): Promise<ChatSearchHit[]>;
}
