import type { CompletionOptions, CompletionStream } from '../types.js';

/** A single conversation — TZ §9.1. */
export interface Chat {
  /**
   * Set by the caller, not force-generated by the library (except a
   * convenient default in `createChat()`, TZ §9.6) — lets a host app reuse
   * its own chat ids directly, without an id-mapping layer.
   */
  id: string;
  title: string;
  createdAt: string;
  updatedAt: string;
  metadata?: Record<string, unknown>;
}

/** A single message within a chat — TZ §9.1. */
export interface ChatMessage {
  /** Set by the caller; unique per `(chatId, id)`, not globally — TZ §9.1. */
  id: string;
  chatId: string;
  role: 'system' | 'user' | 'assistant';
  content: string;
  /**
   * `'complete'` — finished normally. `'cancelled'` — generation was
   * aborted via `AbortSignal`; `content` is the partial response and is
   * kept, not discarded. `'error'` — generation failed at runtime;
   * `content` may be empty. User messages are always `'complete'`. TZ §9.8.
   */
  status: 'complete' | 'cancelled' | 'error';
  createdAt: string;
  tokenCount?: number;
  metadata?: Record<string, unknown>;
}

/**
 * Mandatory MVP surface — library as source of truth for chat data
 * (Mode A, TZ §9.6). Implemented by `LocalAiClient`, backed by
 * `ConversationStore`.
 */
export interface ConversationApi {
  createChat(options?: {
    id?: string;
    title?: string;
    systemPrompt?: string;
    metadata?: Record<string, unknown>;
  }): Promise<Chat>;
  listChats(options?: { limit?: number; offset?: number; orderBy?: 'updatedAt' | 'createdAt' }): Promise<Chat[]>;
  getChat(chatId: string): Promise<Chat | null>;
  renameChat(chatId: string, title: string): Promise<void>;
  /** Cascades to messages and the chat's session-cache file, TZ §9.2. */
  deleteChat(chatId: string): Promise<void>;
  getMessages(chatId: string, options?: { limit?: number; before?: string }): Promise<ChatMessage[]>;

  /**
   * Loads chat history, streams a completion, and persists both the user
   * and assistant messages itself (custom ids accepted for idempotent
   * retry after a network failure). Cancel/error semantics: TZ §9.8.
   * Context-window handling: TZ §9.7.
   */
  sendMessage(
    chatId: string,
    text: string,
    options?: {
      userMessageId?: string;
      assistantMessageId?: string;
      completionOptions?: CompletionOptions;
      signal?: AbortSignal;
    },
  ): CompletionStream<ChatMessage>;
}

/**
 * Optional extension — library as a context mirror over externally owned
 * history (Mode B, TZ §9.6). The same `LocalAiClient` implements it; apps
 * that don't need sync simply never call these. Kept as a separate type
 * (not folded into `ConversationApi`) to avoid inflating the surface for
 * consumers who only need Mode A — see TZ §9.2, open question §16.16 on
 * whether this ships in the first release at all.
 */
export interface ConversationSyncApi {
  /**
   * Idempotent upsert by id: creates the chat if missing; if it already
   * exists, only `title`/`metadata`/`updatedAt` are updated — messages are
   * never touched or lost. TZ §9.2.
   */
  upsertChat(chat: {
    id: string;
    title: string;
    createdAt?: string;
    updatedAt?: string;
    metadata?: Record<string, unknown>;
  }): Promise<Chat>;

  /**
   * Idempotent append: dedups by `(chatId, message.id)`, silently skipping
   * (never overwriting — content is immutable after first write, TZ
   * §9.5/§9.6) messages that already exist. Creates the chat via an implicit
   * minimal `upsertChat` if `chatId` doesn't exist yet. Insert order doesn't
   * matter — reads are sorted by `createdAt`. TZ §9.2.
   */
  appendMessages(
    chatId: string,
    messages: Array<{
      id: string;
      role: ChatMessage['role'];
      content: string;
      status?: ChatMessage['status'];
      createdAt: string;
      tokenCount?: number;
      metadata?: Record<string, unknown>;
    }>,
  ): Promise<{ inserted: number; skippedExisting: number }>;
}
